### ISSUE TITLE
helm gcs rm not functioning properly

### ISSUE THREAD

**Issue by tdigangi** [hayorov/helm-gcs#51] opened 2020-05-20 15:24 UTC
**VERSION**
helm-gcs = Version 0.3.0

**COMMAND**
`helm gcs rm gcp-helm-project repo`

**ISSUE**
[RemoveChart](https://github.com/hayorov/helm-gcs/blob/290becde973a736ac7ab4fcbdc2d6268e6cac667/pkg/repo/repo.go#L159) Appears to remove the chart from the index.yaml, but the tgz remains in the bucket. I see the following error.

```bash
helm gcs remove gcp-helm-project repo --debug
Error: delete: storage: object doesn't exist
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

delete: storage: object doesn't exist
Error: plugin "gcs" exited with error
helm.go:84: [debug] plugin "gcs" exited with error
```

**index.yaml**
```yaml
apiVersion: v1
entries:
  gcp-helm-project:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-05-20T10:47:06.307038-04:00"
    description: A Helm chart.
    digest: 234254356fdtgdfgsdg334534534535
    name: gcp-helm-project
    type: application
    urls:
    - gs://[BUCKET]/platform/gcp-helm-project-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-20T10:47:06.307042-04:00"
```

**Comment by Vlad1mir-D** [comment] 2021-04-15 10:56
@hayorov Why closed?

**Comment by Vlad1mir-D** [comment] 2021-06-17 00:13
Brilliant...

**Comment by hayorov** [comment] 2021-06-21 03:47
Cannot reproduce, could you please add more details or steps to reproduce.

## Scenario

- Check bucket 

```
 ❯ helm repo list       
NAME              	URL                                      
test              	gs://gcs-helm  
```

```
 ❯ gsutil ls gs://gcs-helm/  
gs://gcs-helm/index.yaml
```
- upload chart and check again

```
❯ helm gcs push test-0.1.0.tgz test 

 ❯ gsutil ls gs://gcs-helm/             
gs://gcs-helm/index.yaml
gs://gcs-helm/test-0.1.0.tgz
```

- rm chart and check again
```
 ❯ helm gcs rm test test
 ❯ gsutil ls gs://gcs-helm/
gs://gcs-helm/index.yaml
```

**Comment by Vlad1mir-D** [comment] 2021-06-24 21:47
Hi @hayorov, thank you for your response.

Here is the full command history of reproduced issue:

```
# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)

# helm version
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}

# helm plugin list
NAME	VERSION	DESCRIPTION

# helm plugin install https://github.com/hayorov/helm-gcs.git
Installing helm-gcs 0.3.12 ...
helm-gcs 0.3.12 is correctly installed.

Init a new repository:
  helm gcs init gs://bucket/path

Add your repository to Helm:
  helm repo add repo-name gs://bucket/path

Push a chart to your repository:
  helm gcs push chart.tar.gz repo-name

Update Helm cache:
  helm repo update

Get your chart:
  helm fetch repo-name/chart

Installed plugin: gcs

# helm plugin list
NAME	VERSION	DESCRIPTION
gcs 	0.3.12 	Manage repositories on Google Cloud Storage

# helm repo add testrepo gs://testrepo-helm/
"testrepo" has been added to your repositories

# gsutil version
gsutil version: 4.61

# gsutil versioning get gs://testrepo-helm/
gs://testrepo-helm: Enabled

# gsutil ls gs://testrepo-helm/
gs://testrepo-helm/chart-a-0.0.1.tgz
gs://testrepo-helm/chart-a-0.0.3.tgz
gs://testrepo-helm/chart-a-0.0.4.tgz
gs://testrepo-helm/chart-a-0.0.5.tgz
[..]
gs://testrepo-helm/index.yaml
gs://testrepo-helm/chart-b-0.1.tgz
[..]

# gsutil cat gs://testrepo-helm/index.yaml
apiVersion: v1
entries:
  chart-a:
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.1.tgz
    version: 0.0.1
[..]
  chart-b:
  - apiVersion: v2
    appVersion: 0.1.0
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-b-0.1.tgz
    version: "0.1"
[..]

# helm gcs rm chart-b testrepo --debug
Error: delete: storage: object doesn't exist
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

delete: storage: object doesn't exist
Error: plugin "gcs" exited with error
helm.go:81: [debug] plugin "gcs" exited with error

# helm gcs rm chart-a testrepo --version 0.0.5 --debug
Error: delete: storage: object doesn't exist
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

delete: storage: object doesn't exist
Error: plugin "gcs" exited with error
helm.go:81: [debug] plugin "gcs" exited with error

# gsutil ls gs://testrepo-helm/
gs://testrepo-helm/chart-a-0.0.1.tgz
gs://testrepo-helm/chart-a-0.0.3.tgz
gs://testrepo-helm/chart-a-0.0.4.tgz
gs://testrepo-helm/chart-a-0.0.5.tgz
[..]
gs://testrepo-helm/index.yaml
gs://testrepo-helm/chart-b-0.1.tgz
[..]

# gsutil cat gs://testrepo-helm/index.yaml
apiVersion: v1
entries:
  chart-a:
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.1
[..]
    type: application
    urls:
    - gs://testrepo-helm/chart-a-0.0.1.tgz
    version: 0.0.1
[..]
```

Also I did prepare test case for this issue intended to be reproduced in a completely fresh environment (inside Docker).
Steps to reproduce:
1. Install and configure docker, google-cloud-sdk (`gcloud init`) 
2. Run following commands:
```
mkdir helm-gcs-rm-test
cd helm-gcs-rm-test
curl -o Dockerfile https://gist.githubusercontent.com/Vlad1mir-D/8281156c90b75e60d33d172878d96024/raw/4ac2675bf01c5d81b2dc53e2bb23bc52cee68632/Dockerfile
docker build -t helm-gcs-rm-test .
docker run -it -v ~/.config/gcloud:/root/.config/gcloud helm-gcs-rm-test
```
Last command will reproduce this issue and output something like that:
```
++ mktemp -u helm-gcs-rm-test-XXXXXXXXXX
++ tr '[:upper:]' '[:lower:]'
+ testbucket=helm-gcs-rm-test-wksxste2al
+ gsutil mb gs://helm-gcs-rm-test-wksxste2al/
Creating gs://helm-gcs-rm-test-wksxste2al/...
+ helm gcs init gs://helm-gcs-rm-test-wksxste2al
+ helm repo add test gs://helm-gcs-rm-test-wksxste2al/
"test" has been added to your repositories
+ helm create sample
Creating sample
+ helm package sample
Successfully packaged chart and saved it to: /sample-0.1.0.tgz
+ helm gcs push sample-0.1.0.tgz test
+ gsutil cat gs://helm-gcs-rm-test-wksxste2al/index.yaml
apiVersion: v1
entries:
  sample:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-06-24T21:45:46.223630421Z"
    description: A Helm chart for Kubernetes
    digest: 201a21df43091122ef39dd9608e5f734ee16ac8702859600cb1035e7b1bf8f21
    name: sample
    type: application
    urls:
    - gs://helm-gcs-rm-test-wksxste2al/sample-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-24T21:45:46.223631983Z"
+ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "test" chart repository
Update Complete. ⎈Happy Helming!⎈
+ helm gcs rm sample test
Error: delete: storage: object doesn't exist
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

delete: storage: object doesn't exist
Error: plugin "gcs" exited with error
+ gsutil ls gs://helm-gcs-rm-test-wksxste2al/
gs://helm-gcs-rm-test-wksxste2al/index.yaml
gs://helm-gcs-rm-test-wksxste2al/sample-0.1.0.tgz
+ gsutil cat gs://helm-gcs-rm-test-wksxste2al/index.yaml
apiVersion: v1
entries: {}
generated: "2021-06-24T21:45:50.951277687Z"
+ gsutil rm 'gs://helm-gcs-rm-test-wksxste2al/*'
Removing gs://helm-gcs-rm-test-wksxste2al/index.yaml...
Removing gs://helm-gcs-rm-test-wksxste2al/sample-0.1.0.tgz...                   
/ [2 objects]                                                                   
Operation completed over 2 objects.                                              
+ gsutil rb gs://helm-gcs-rm-test-wksxste2al
Removing gs://helm-gcs-rm-test-wksxste2al/...
```

**Comment by Vlad1mir-D** [comment] 2021-06-25 07:00
@hayorov I will be very thankful to you if you'll be able to fix this issue as I attempted to use Helm OCI and it seems that your plugin allows to implement more powerful and convenient workflows than embedded Helm OCI when used together with GCP.

Anyway thank you for this great plugin!

**Comment by hayorov** [comment] 2021-06-28 09:06
Hello @Vlad1mir-D  many thanks, could you please `run rm` command and `rm -v` with `HELM_GCS_DEBUG=true`
e.g:
```bash
 ~/workspace/test-chart 
 ❯ helm gcs push /Users/alexk/workspace/test-chart/test-0.1.1.tgz test

 ~/workspace/test-chart 
 ❯ HELM_GCS_DEBUG=true helm gcs rm test test                          
DEBU[0000] helm repo file: /Users/alexk/Library/Preferences/helm/repositories.yaml 
DEBU[0000] removing chart test-                         
DEBU[0000] load index file "gs://gcs-helm/index.yaml"   
DEBU[0000] index file generation: 1624871157755288      
DEBU[0000] test-0.1.1 will be deleted                   
DEBU[0000] push index file                              
DEBU[0000] update condition: if generation = 1624871157755288 
DEBU[0000] delete gcs file gs://gcs-helm/test-0.1.1.tgz 

```

**Comment by Vlad1mir-D** [comment] 2021-06-29 17:59
Hi, @hayorov 

1. 
```
# HELM_GCS_DEBUG=true helm gcs rm kommon testrepo --debug --version 0.0.1
DEBU[0000] helm repo file: /home/username/.config/helm/repositories.yaml 
DEBU[0000] removing chart kommon-0.0.1                  
DEBU[0000] load index file "gs://testrepo-helm/index.yaml" 
DEBU[0000] index file generation: 1624989203460726      
DEBU[0000] kommon-0.0.1 will be deleted                 
DEBU[0000] push index file                              
DEBU[0000] update condition: if generation = 1624989203460726 
DEBU[0001] delete gcs file gs://testrepo-helm//kommon-0.0.1.tgz 
Error: delete: storage: object doesn't exist
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

delete: storage: object doesn't exist
Error: plugin "gcs" exited with error
helm.go:81: [debug] plugin "gcs" exited with error

# HELM_GCS_DEBUG=true helm gcs rm kommon testrepo --debug
DEBU[0000] helm repo file: /home/username/.config/helm/repositories.yaml 
DEBU[0000] removing chart kommon-                       
DEBU[0000] load index file "gs://testrepo-helm/index.yaml" 
DEBU[0000] index file generation: 1624989216325864      
Error: chart "kommon" not found
Usage:
  helm-gcs rm [chart] [repository] [flags]

Aliases:
  rm, remove

Flags:
  -h, --help             help for rm
      --retry            retry if the index changed
  -v, --version string   version of the chart to remove

Global Flags:
      --debug                    activate debug
      --service-account string   service account to use for GCS

chart "kommon" not found
Error: plugin "gcs" exited with error
helm.go:81: [debug] plugin "gcs" exited with error
```


2. I'm not using service account, I'm using plain IAM user account and it has `owner` role assigned.
I'm pretty sure there are no permissions issue as I'm able to remove file directly using `gsutil rm` using the same credentials.

**Comment by Vlad1mir-D** [comment] 2021-08-19 14:01
It seems that "stale bot" is a good option to make software look perfect.
Meh

**Comment by Vlad1mir-D** [comment] 2021-08-19 14:03
Also it's cheaper than setting "WONTFIX".

**Comment by Vlad1mir-D** [comment] 2021-08-19 14:03
Because this bot will do that for you.

**Comment by hayorov** [comment] 2021-08-24 14:53
@Vlad1mir-D I've tried to reproduce the bug and don't see the issue :(

Index file before rm
```
apiVersion: v1
entries:
  test-a:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-24T22:43:47.927978+08:00"
    description: A Helm chart for Kubernetes
    digest: 4186a4345339db90bc24e231481bfce1416f21069d0b5ae15958885542cdefa4
    name: test-a
    type: application
    urls:
    - gs://gcs-helm/test-a-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-24T22:41:25.777923+08:00"
    description: A Helm chart for Kubernetes
    digest: a68b7a2263f429f459e11796df7a4d37c690aa260c7a3edd7521668fafd15922
    name: test-a
    type: application
    urls:
    - gs://gcs-helm/test-a-0.1.0.tgz
    version: 0.1.0
  test-b:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-24T22:44:50.327747+08:00"
    description: A Helm chart for Kubernetes
    digest: 74327923d19728ea45aa8cb2ff5675cfdf9e71a1e0f51c2220f31ba08d4c1313
    name: test-b
    type: application
    urls:
    - gs://gcs-helm/test-b-3.1.0.tgz
    version: 3.1.0
generated: "2021-08-24T22:44:50.327753+08:00"
```
rm test-a app (has 2 versions)
```
 ❯ helm gcs rm test-a testXXX                                                                                                ◼ ⬇
DEBU[0000] helm repo file: /Users/alexk/Library/Preferences/helm/repositories.yaml 
DEBU[0000] removing chart test-a-                       
DEBU[0000] load index file "gs://gcs-helm/index.yaml"   
DEBU[0000] index file generation: 1629816290537727      
DEBU[0000] test-a-1.1.0 will be deleted                 
DEBU[0000] test-a-0.1.0 will be deleted                 
DEBU[0000] push index file                              
DEBU[0000] update condition: if generation = 1629816290537727 
DEBU[0001] delete gcs file gs://gcs-helm/test-a-1.1.0.tgz 
DEBU[0001] delete gcs file gs://gcs-helm/test-a-0.1.0.tgz 
```

Could you please help one more time?

I'd like to double-check the steps?

1. init gcs repo `helm gcs init gs://gcs-helm`
2. add repo `helm repo add testXXX gs://gcs-helm `
3. generate and package test-a and test-b charts with multiple versions 
4. push multiple packages
4. check the index file and packages
5. run app-a deletion (w/o version) `helm gcs rm test-a testXXX`

**Comment by TejaBeta** [comment] 2021-09-16 16:41
@Vlad1mir-D  @hayorov 
I was able to replicate this issue. This happens when we append `/` at the end of helm repo.

```
$ helm repo add mybucket gs://my-bucket/ 
"mybucket" has been added to your repositories

$ helm repo list
NAME       URL                          
mybucket gs://my-bucket/ 
```

Quick fix is by not appending `/` to the repo name 😬

This [PR](https://github.com/hayorov/helm-gcs/pull/103) will eliminate those issues I believe, along with one more issue with rm cmd 😀

**Comment by hayorov** [comment] 2021-09-21 12:49
@TejaBeta  many thanks, awesome.

Finally resolved :)

**Closed by hayorov** 2021-09-21 12:49 UTC
Labels: bug
